version: '3.5'

services:
  db:
    container_name: fastapi_project
    image: postgres:14.3-alpine
    env_file:
      - .env
    ports:
      - "5432:5432"
    environment:
      - POSTGRES_DB=${DB_NAME}
      - POSTGRES_PASSWORD=${DB_PASS}
      - POSTGRES_USER=${DB_USER}
